management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  prometheus:
    metrics:
      export:
        enabled: true
