version: "3"

services:
  prometheus:
    container_name: sbs_prometheus
    image: prom/prometheus:v2.27.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - default

  grafana:
    container_name: sbs_grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:

