version: "3"

services:
  prometheus:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: sbs_prometheus
    image: prom/prometheus:v2.27.1
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090" ]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: sbs_grafana
    image: grafana/grafana:7.5.7
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3030" ]
      interval: 10s
      timeout: 10s
      retries: 10
